### ISSUE TITLE
Running in the base case

### ISSUE THREAD

**Issue by dbaltieri** [Yayap13/byzantine#1]
I'm trying to run the byzantine.erl file using N = 3 M=0 A=1, but the process just crash. Could you explain what does it means ?

**Comment by Yayap13** [comment]
Can you paste the error you are getting?
I just tested it again and it's working fine for me.

But be aware that testing the signed messages (A=1) with a number of traitors (M=0) will end the program and display a message saying that there are no traitors.

Maybe test it with: byzantine:master(4,1,1)

**Comment by dbaltieri** [comment]
In fact, I would like to test it using the OM, just to guarantee that it's running in the base case. This is the code lines that I'm trying to change.` % Apenas em caso de o algoritmo ser diferente de 3f+1
        {start_oral_message_algo, Traitors, _} when Traitors<0 ->
            io:format("O general (~p):: Pas de traitres == Pas de calculs!~n", [self()]);

        % Esta mensagem é para configurar e iniciar o algoritmo de mensagens assinadas para cada general
        {start_signed_message_algo, _Traitors, _} ->
            %io:format("O general (~p):: inicia a mensagem, passando recebi!~n", [self()]),

            [FirstGeneral|RestGenerals] = GeneralsInfo,
            CommanderPid = get_pid_from_generalsinfo(FirstGeneral),
            if
                self()==CommanderPid ->
                    %io:format("O general(~p):: Eu sou o comandante!~n", [self()]),
                    print_vote_decision(AttackDecision, IsTraitor),
                    send_to_all_other_generals(RestGenerals, decisionSigned, {AttackDecision, []}, IsTraitor);
                self()/=CommanderPid ->
                    general(signedMessage, RestGenerals, [], 1, IsTraitor, MasterPid)
            end
            
            %general(signedMessage, GeneralsInfo, -1, IsTraitor, MasterPid)
    end.`

**Comment by Yayap13** [comment]
I'm sorry but this algorithm wasn't designed to work without any traitors.
That's why I was checking and printing this error in case you wanted to run it anyway.
If you want to implement this behaviour, maybe a better option will be to rewrite the logic from the ground up.
